services:
    chanager:
        container_name: chanager
        build:
            context: .
            dockerfile: Dockerfile-tcp
        environment:
            CHANAGER_IP: "172.20.1.1" 
            CHANAGER_WAIT_TO_CONNECT: 2
            CHANAGER_CLIENT_HEALTH_CHECK_INTERVAL: 5
            RLS_PORT: 8000
            ALS_PORT: 1300
            CMD_PORT: 8001
            LOGLEVEL: "info"
        ports:
          - "8000:8001"
        networks:
            static-network:
                ipv4_address: 172.20.1.1
        command: ["python", "app/chmng.py"]

    client-5:
        container_name: client-5
        build:
            context: .
            dockerfile: Dockerfile-tcp
        environment:
            CHANAGER_IP: "172.20.1.1"
            CHANAGER_WAIT_TO_CONNECT: 2
            CHANAGER_CLIENT_HEALTH_CHECK_INTERVAL: 5
            RLS_PORT: 8000
            ALS_PORT: 1300
            CMD_PORT: 8001
            CLIENT_NAME: "Client-5"
            CLIENT_CLS_PORT: 8000
            CLIENT_IP: "172.20.1.5"
            LOGLEVEL: "info"
        networks:
            static-network:
                ipv4_address: 172.20.1.5
        command: ["python", "app/client.py", "1"]
        depends_on:
            - chanager
    client-10:
        container_name: client-10
        build:
            context: .
            dockerfile: Dockerfile-tcp
        environment:
            CHANAGER_IP: "172.20.1.1"
            CHANAGER_WAIT_TO_CONNECT: 2
            CHANAGER_CLIENT_HEALTH_CHECK_INTERVAL: 5
            RLS_PORT: 8000
            ALS_PORT: 1300
            CMD_PORT: 8001
            CLIENT_NAME: "Client-5"
            CLIENT_CLS_PORT: 8000
            CLIENT_IP: "172.20.1.10"
            LOGLEVEL: "info"
        networks:
            static-network:
                ipv4_address: 172.20.1.10
        command: ["python", "app/client.py", "1"]
        depends_on:
            - chanager

networks:
    static-network:
       driver: bridge
       ipam:
           config:
               - subnet: 172.20.0.0/16
